version: '3'
services:

  test:
    image: alpine
    tty: true
    command: | 
      /bin/sh -c "mkdir -p /tmp/foo; 
        date > /tmp/foo/bla ; 
        /bin/sh"

  test2:
    image: alpine
    tty: true
    command: >
      /bin/sh -c "mkdir -p /tmp/foo; 
        date | sed 's/[a-z]/U/g' > /tmp/foo/bla ; 
        /bin/sh"


