version: '3'
services:
  service1:
    image: nginx
    volumes:
      - vol1:/vol1
      - vol1:/vol2:ro

volumes:
  vol1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/mount"


